### ISSUE TITLE
ZVEI Filter

### ISSUE THREAD

**Issue by Hobo2k** [Smith-fms/raspoc#1]
Hallo,

Ich bin im Script über die Zeile:
      zvei_filter = ['00000', '11111', '22222', '33333', '44444', '55555', '66666', '77777', '88888', '99999']
gestolpert.
Wie muss ich diese beispielweise für ne ganze Range anpassen?
Also z.B. 12310 bis 12386 oder 43xxx ?

Was passiert, wenn man diese auskommentiert?

Dazu die Frage, werden die genannten Schleifen ausgeschlossen, oder nur diese behandelt?

Danke,
Hobo2k

**Comment by Schrolli91** [comment]
Siehe ab zeile 139:
Schleifen filtern 00000, 11111, ... 
if address == any(zvei_filter) :
print address + " - ZVEI ausgefiltert - nichts unternommen"

Die werden also von der Auswertung ausgeschlossen

**Comment by Hobo2k** [comment]
Super Danke!
